main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', views.about, name='about'),
    path('create', views.create, name='create'),
    path('search', views.search, name='search'),
    path('create_accessories', views.create_accessories, name='create_accessories'),
    path('home_accessories', views.home_accessories, name='home_accessories'),
    path('search_accessories', views.search_accessories, name='search_accessories'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

main/models.py
from django.db import models



class Task(models.Model):
    class Meta:
        verbose_name = "Данные полуфабриката"
        verbose_name_plural = "Данные полуфабриката"
        ordering = [
            '-release_date']

    details_name = models.CharField("Дельта", max_length=100, blank=True)
    code = models.CharField("Код детали", max_length=50, blank=True)
    color_code = models.CharField("Код цвета", max_length=50, blank=True)
    quantity_actual = models.CharField("Фактический остаток", max_length=50, blank=True)
    quantity_1c = models.CharField("Остаток 1с", max_length=50, blank=True)
    delta = models.CharField("Дельта", max_length=50, blank=True)
    adjustments = models.CharField("Корректировка", max_length=50, blank=True)
    adjustments_marriage = models.CharField("Списание в брак", max_length=50, blank=True)
    actual_registration = models.CharField("Постановка на учет", max_length=50, blank=True)
    after_adjustment_quantity_actual = models.CharField("Фактический остаток после корректировки",
                                                        max_length=50, blank=True)
    after_adjustment_quantity_1c = models.CharField("Остаток 1с после корректировки", max_length=50, blank=True)
    after_adjustment_delta = models.CharField("Дельта после корректировки", max_length=50, blank=True)
    release_date = models.DateField("Дата пересчета")

    def __str__(self):
        return self.details_name


class Accessories(models.Model):
    class Meta:
        verbose_name = "Данные комплектующих"
        verbose_name_plural = "Данные комплектующих"
        ordering = [
            '-release_date']

    details_name = models.CharField("Дельта", max_length=100, blank=True)
    code = models.CharField("Код детали", max_length=50, blank=True)
    quantity_actual = models.CharField("Фактический остаток", max_length=50, blank=True)
    quantity_1c = models.CharField("Остаток 1с", max_length=50, blank=True)
    delta = models.CharField("Дельта", max_length=50, blank=True)
    adjustments = models.CharField("Корректировка", max_length=50, blank=True)
    adjustments_marriage = models.CharField("Списание в брак", max_length=50, blank=True)
    actual_registration = models.CharField("Постановка на учет", max_length=50, blank=True)
    after_adjustment_quantity_actual = models.CharField("Фактический остаток после корректировки",
                                                        max_length=50, blank=True)
    after_adjustment_quantity_1c = models.CharField("Остаток 1с после корректировки", max_length=50, blank=True)
    after_adjustment_delta = models.CharField("Дельта после корректировки", max_length=50, blank=True)
    release_date = models.DateField("Дата пересчета")

    def __str__(self):
        return self.details_name

main/forms.py
from .models import Task, Accessories
from django.forms import ModelForm, TextInput, DateInput


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["details_name", "code", "color_code", "quantity_actual", "quantity_1c", "delta", "adjustments",
                  "after_adjustment_quantity_actual", "after_adjustment_quantity_1c", "after_adjustment_delta",
                  "adjustments_marriage", "release_date", "actual_registration"]
        widgets = {
            'details_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название детали'
            }),
            'code': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Код детали'
            }),
            'color_code': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Код цвета'
            }),
            'quantity_actual': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фактический остаток'
            }),
            'quantity_1c': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Остаток 1с'
            }),
            'delta': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дельта'
            }),
            'adjustments': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Корректировка'
            }),
            'adjustments_marriage': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Списание в брак'
            }),
            'actual_registration': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Постановка на учет'
            }),
            'after_adjustment_quantity_actual': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фактический остаток после корректировки'
            }),
            'after_adjustment_quantity_1c': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Остаток 1с после корректировки'
            }),
            'after_adjustment_delta': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дельта после корректировки'
            }),
            'release_date': DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата пересчета'
            }),

        }


class AccessoriesForm(ModelForm):
    class Meta:
        model = Accessories
        fields = ["details_name", "code", "quantity_actual", "quantity_1c", "delta", "adjustments",
                  "after_adjustment_quantity_actual", "after_adjustment_quantity_1c", "after_adjustment_delta",
                  "adjustments_marriage", "release_date", "actual_registration"]
        widgets = {
            'details_name': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название детали'
            }),
            'code': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Код детали'
            }),
            'quantity_actual': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фактический остаток'
            }),
            'quantity_1c': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Остаток 1с'
            }),
            'delta': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дельта'
            }),
            'adjustments': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Корректировка'
            }),
            'adjustments_marriage': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Списание в брак'
            }),
            'actual_registration': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Постановка на учет'
            }),
            'after_adjustment_quantity_actual': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фактический остаток после корректировки'
            }),
            'after_adjustment_quantity_1c': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Остаток 1с после корректировки'
            }),
            'after_adjustment_delta': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дельта после корректировки'
            }),
            'release_date': DateInput(attrs={
                'class': 'form-control',
                'placeholder': 'Дата пересчета'
            }),
        }

main/views.py
from .models import Task, Accessories
from .forms import TaskForm, AccessoriesForm
from django.shortcuts import render


def index(request):
    tasks = Task.objects.all()
    return render(request, 'main/index.html', {'details_name': 'Главная страница сайта', 'tasks': tasks})


def home_accessories(request):
    accessories = Accessories.objects.all()
    return render(request, 'main/home_accessories.html', {'details_name': 'Главная страница сайта',
                                                          'accessories': accessories})


def about(request):
    return render(request, 'main/about.html')


def create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            if obj.after_adjustment_quantity_actual == "":
                obj.after_adjustment_quantity_actual = obj.quantity_actual
            else:
                obj.after_adjustment_quantity_actual = obj.after_adjustment_quantity_actual

            if obj.after_adjustment_quantity_1c == "":
                if obj.adjustments != "0" and obj.adjustments != "":
                    obj.after_adjustment_quantity_1c = str(int(obj.quantity_1c) + int(obj.adjustments))
                    if int(obj.adjustments) >= 1 and int(obj.delta) >= 1:
                        obj.after_adjustment_delta = str(int(obj.delta) - int(obj.adjustments))
                    elif int(obj.adjustments) <= -1 and int(obj.delta) <= -1:
                        obj.after_adjustment_delta = str(int(obj.delta) - int(obj.adjustments))
                    elif int(obj.adjustments) <= -1 and int(obj.delta) >= 1:
                        obj.after_adjustment_delta = str(int(obj.delta) + int(obj.adjustments))
                    elif int(obj.adjustments) >= 1 and int(obj.delta) <= -1:
                        obj.after_adjustment_delta = str(int(obj.delta) + int(obj.adjustments))
            else:
                obj.after_adjustment_quantity_1c = obj.after_adjustment_quantity_1c

            if obj.after_adjustment_delta == "":
                obj.after_adjustment_delta = obj.delta
            else:
                obj.after_adjustment_delta = obj.after_adjustment_delta
            obj.save()

    form = TaskForm()
    name = Task.objects.filter().order_by('-id')[:1]
    context = {
        'form': form,
        'name': name
    }
    return render(request, 'main/create.html', context)


def create_accessories(request):
    if request.method == 'POST':
        form = AccessoriesForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            if obj.after_adjustment_quantity_actual == "":
                obj.after_adjustment_quantity_actual = obj.quantity_actual
            else:
                obj.after_adjustment_quantity_actual = obj.after_adjustment_quantity_actual

            if obj.after_adjustment_quantity_1c == "":
                obj.after_adjustment_quantity_1c = obj.quantity_1c
            else:
                obj.after_adjustment_quantity_1c = obj.after_adjustment_quantity_1c

            if obj.after_adjustment_delta == "":
                obj.after_adjustment_delta = obj.delta
            else:
                obj.after_adjustment_delta = obj.after_adjustment_delta

            obj.save()

    form = AccessoriesForm()
    name = Accessories.objects.filter().order_by('-id')[:1]
    context = {
        'form': form,
        'name': name
    }
    return render(request, 'main/create_accessories.html', context)

#
# def create_accessories(request):
#     name = Accessories.objects.all()
#     return render(request, 'main/create_accessories.html', {'name': name})


def search(request):
    queryset = request.GET.get('q', '')
    queryset = queryset.split()

    if queryset:
        try:
            task = Task.objects.filter(code__exact=queryset[0], color_code__exact=queryset[1])
        except IndexError:
            task = Task.objects.filter(code__exact=queryset[0])

    else:
        task = Task.objects.all()
    return render(request, 'main/search.html', {'details_name': 'Главная страница сайта', 'task': task})


def search_accessories(request):
    queryset = request.GET.get('q', '')

    if queryset:
        try:
            task = Accessories.objects.filter(code__iexact=queryset)
        except AttributeError:
            print("abra kadabra")

    else:
        task = Accessories.objects.all()
    return render(request, 'main/search_accessories.html', {'details_name': 'Главная страница сайта', 'task': task})

main/templates/main/create.html
<!doctype html>
<html lang="ru">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Добавить</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">



</head>
<body>

         <nav style="text-align:right" class="my-2 my-md-0 mr-md-3">
        <a href="{% url 'home' %}" class="pressed-button">Данные полуфабрикат</a>
        <a href="{% url 'home_accessories' %}" class="pressed-button">Данные комплектующие</a>
        <a href="{% url 'about' %}" class="pressed-button">Удалить</a>
        <a href="{% url 'create' %}" class="pressed-button">Добавить пересчет полуфабриката</a>
        <a href="{% url 'create_accessories' %}" class="pressed-button">Добавить пересчет комплектующих</a>
        </nav>

    <dialog id="dialog" style="">
  <p>
      <table  border="1" cellpadding="4" cellspacing="0">
            <tr>
                <th bgcolor="#AFEEEE" width="300"> Название детали</th>
                <th bgcolor="#AFEEEE"> Код детали</th>
                <th bgcolor="#AFEEEE"> Код цвета</th>
                <th bgcolor="#F5DEB3"> Фактический остаток</th>
                <th bgcolor="#F5DEB3"> Остаток 1с</th>
                <th bgcolor="#F5DEB3"> Дельта</th>
                <th bgcolor="#DAA520"> Корректировка</th>
                <th bgcolor="#DAA520"> Списание в брак</th>
                <th bgcolor="#DAA520"> Постановка на учет</th>
                <th bgcolor="#00FA9A"> Фактический остаток после корректировки</th>
                <th bgcolor="#00FA9A"> Остаток 1с после корректировки</th>
                <th bgcolor="#00FA9A"> Дельта после корректировки</th>
                <th> Дата пересчета</th>
            </tr>
            {% for el in name %}
            <tr>
                <td bgcolor="#AFEEEE" >{{ el.details_name }}</td>
                <td bgcolor="#AFEEEE">{{ el.code }}</td>
                <td bgcolor="#AFEEEE">{{ el.color_code }}</td>
                <td bgcolor="#F5DEB3">{{ el.quantity_actual }}</td>
                <td bgcolor="#F5DEB3">{{ el.quantity_1c }}</td>
                <td bgcolor="#F5DEB3">{{ el.delta }}</td>
                <td bgcolor="#DAA520">{{ el.adjustments }}</td>
                <td bgcolor="#DAA520">{{ el.adjustments_marriage }}</td>
                <td bgcolor="#DAA520">{{ el.actual_registration }}</td>
                <td bgcolor="#00FA9A">{{ el.after_adjustment_quantity_actual }}</td>
                <td bgcolor="#00FA9A">{{ el.after_adjustment_quantity_1c }}</td>
                <td bgcolor="#00FA9A">{{ el.after_adjustment_delta }}</td>
                <td>{{ el.release_date }}</td>
            </tr>
            {% endfor %}
        </table>
  </p>


</dialog>


<script type = text/javascript>
var dialog = document.getElementById('dialog');
dialog.show();
document.getElementById('dialog').style.height = 'Auto-px';
var dialog = document.querySelector('dialog');

document.querySelector('#close').onclick = function() {
  dialog.close();
};
</script>
    <div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <h1 style="text-align:left">Страница добавления пересчета полуфабриката</h1>
        <br>
    </div>

            <script type="text/javascript">
        $(function() {
            $("#id_details_name").focus();
        });
    </script>

    <form id="123" method="post">
        {% csrf_token %}
        {{ form.details_name }}<br>
        {{ form.code }}<br>
        {{ form.color_code }}<br>
        {{ form.quantity_actual }}<br>
        {{ form.quantity_1c }}<br>
        {{ form.delta }}<br>
        {{ form.adjustments }}<br>
        {{ form.adjustments_marriage }}<br>
        {{ form.actual_registration }}<br>
        {{ form.after_adjustment_quantity_actual }}<br>
        {{ form.after_adjustment_quantity_1c }}<br>
        {{ form.after_adjustment_delta }}<br>
        {{ form.release_date }}<br>
        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
       <script type="text/javascript">
        $('input').live("keypress", function (e) {
        /* ENTER PRESSED*/
        var OffSet = 0;
        if (e.keyCode == 13) {
            /* FOCUS ELEMENT */
            if ($(this).is("input[type='radio']")) {
                var tblID = $(this).closest('table').attr('id');
                var radios = $('#' + tblID).find(":input");
                //alert(radios.index(this));
                OffSet = radios.length - radios.index(this) - 1;
            }
            //alert(OffSet);

            var inputs = $(this).parents("form").eq(0).find(":input");
            var idx = inputs.index(this);
            inputs[idx + OffSet].blur();

            try {
                inputs[idx + OffSet].selectionStart = inputs[idx + OffSet].selectionEnd = -1;
            } catch (e) {

            }
            if (idx == inputs.length - 1) {
                inputs[0].select();
            } else {
                inputs[idx + 1 + OffSet].focus(); //  handles submit buttons
                try {
                    inputs[idx + 1 + OffSet].select();
                } catch (e) {
                }
            }
            return false;
        }
    });
       </script>


</body>

    <style>
    table {
    border: 3px solid black;
    border-collapse:separate;
    border-spacing: 0;
    width: 100%;
}

table tr td {
    border: 1px solid black;
    word-break: break-all;

}

table tr td:nth-child(2) {
    word-break: break-all;

}
body {
  background: url(https://html5book.ru/wp-content/uploads/2015/10/background54.png);
}
.pressed-button {

  text-decoration: none;
  display: inline-block;
  padding: 12px 40px;
  margin: 10px 20px;
  border-radius: 30px;
  background-image: linear-gradient(45deg, #6ab1d7 0%, #33d9de 50%, #002878 100%);
  background-position: 100% 0;
  background-size: 200% 200%;
  font-family: 'Montserrat', sans-serif;
  font-size: 16px;
  font-weight: 200;
  color: white;
  box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);
  transition: .5s;
}
.pressed-button:hover {
  box-shadow: 0 0 0 0 rgba(0, 40, 120, 0);
  background-position: 0 0;
}

</style>

</html>

main/templates/main/create_accessories.html
<!doctype html>
<html lang="ru">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Добавить</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">



</head>
<body>

         <nav style="text-align:right" class="my-2 my-md-0 mr-md-3">
        <a href="{% url 'home' %}" class="pressed-button">Данные полуфабрикат</a>
        <a href="{% url 'home_accessories' %}" class="pressed-button">Данные комплектующие</a>
        <a href="{% url 'about' %}" class="pressed-button">Удалить</a>
        <a href="{% url 'create' %}" class="pressed-button">Добавить пересчет полуфабриката</a>
        <a href="{% url 'create_accessories' %}" class="pressed-button">Добавить пересчет комплектующих</a>
        </nav>

    <dialog id="dialog" style="">
  <p>
      <table  border="1" cellpadding="4" cellspacing="0">
            <tr>
                <th bgcolor="#AFEEEE" width="300"> Название детали</th>
                <th bgcolor="#AFEEEE"> Код детали</th>
                <th bgcolor="#F5DEB3"> Фактический остаток</th>
                <th bgcolor="#F5DEB3"> Остаток 1с</th>
                <th bgcolor="#F5DEB3"> Дельта</th>
                <th bgcolor="#DAA520"> Корректировка</th>
                <th bgcolor="#DAA520"> Списание в брак</th>
                <th bgcolor="#DAA520"> Постановка на учет</th>
                <th bgcolor="#00FA9A"> Фактический остаток после корректировки</th>
                <th bgcolor="#00FA9A"> Остаток 1с после корректировки</th>
                <th bgcolor="#00FA9A"> Дельта после корректировки</th>
                <th> Дата пересчета</th>
            </tr>
            {% for el in name %}
            <tr>
                <td bgcolor="#AFEEEE" >{{ el.details_name }}</td>
                <td bgcolor="#AFEEEE">{{ el.code }}<br></td>
                <td bgcolor="#F5DEB3">{{ el.quantity_actual }}</td>
                <td bgcolor="#F5DEB3">{{ el.quantity_1c }}</td>
                <td bgcolor="#F5DEB3">{{ el.delta }}</td>
                <td bgcolor="#DAA520">{{ el.adjustments }}</td>
                <td bgcolor="#DAA520">{{ el.adjustments_marriage }}</td>
                <td bgcolor="#DAA520">{{ el.actual_registration }}</td>
                <td bgcolor="#00FA9A">{{ el.after_adjustment_quantity_actual }}</td>
                <td bgcolor="#00FA9A">{{ el.after_adjustment_quantity_1c }}</td>
                <td bgcolor="#00FA9A">{{ el.after_adjustment_delta }}</td>
                <td>{{ el.release_date }}</td>
            </tr>
            {% endfor %}
        </table>
  </p>
<!--  <button id="close" class="btn btn-success">Закрыть</button>-->

</dialog>


<script type = text/javascript>
var dialog = document.getElementById('dialog');
dialog.show();
document.getElementById('dialog').style.height = 'Auto-px';
var dialog = document.querySelector('dialog');

document.querySelector('#close').onclick = function() {
  dialog.close();
};
</script>
    <div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <h1 style="text-align:left">Страница добавления пересчета комплектующих</h1>
        <br>
    </div>

            <script type="text/javascript">
        $(function() {
            $("#id_details_name").focus();
        });
    </script>

    <form id="123" method="post">
        {% csrf_token %}
        {{ form.details_name }}<br>
        {{ form.code }}<br>
        {{ form.quantity_actual }}<br>
        {{ form.quantity_1c }}<br>
        {{ form.delta }}<br>
        {{ form.adjustments }}<br>
        {{ form.adjustments_marriage }}<br>
        {{ form.actual_registration }}<br>
        {{ form.after_adjustment_quantity_actual }}<br>
        {{ form.after_adjustment_quantity_1c }}<br>
        {{ form.after_adjustment_delta }}<br>
        {{ form.release_date }}<br>
        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
       <script type="text/javascript">
        $('input').live("keypress", function (e) {
        /* ENTER PRESSED*/
        var OffSet = 0;
        if (e.keyCode == 13) {
            /* FOCUS ELEMENT */
            if ($(this).is("input[type='radio']")) {
                var tblID = $(this).closest('table').attr('id');
                var radios = $('#' + tblID).find(":input");
                //alert(radios.index(this));
                OffSet = radios.length - radios.index(this) - 1;
            }
            //alert(OffSet);

            var inputs = $(this).parents("form").eq(0).find(":input");
            var idx = inputs.index(this);
            inputs[idx + OffSet].blur();

            try {
                inputs[idx + OffSet].selectionStart = inputs[idx + OffSet].selectionEnd = -1;
            } catch (e) {

            }
            if (idx == inputs.length - 1) {
                inputs[0].select();
            } else {
                inputs[idx + 1 + OffSet].focus(); //  handles submit buttons
                try {
                    inputs[idx + 1 + OffSet].select();
                } catch (e) {
                }
            }
            return false;
        }
    });
       </script>


</body>

    <style>
    table {
    border: 3px solid black;
    border-collapse:separate;
    border-spacing: 0;
    width: 100%;
}

table tr td {
    border: 1px solid black;
    word-break: break-all;

}

table tr td:nth-child(2) {
    word-break: break-all;

}
body {
  background: url(https://html5book.ru/wp-content/uploads/2015/10/background54.png);
}
.pressed-button {

  text-decoration: none;
  display: inline-block;
  padding: 12px 40px;
  margin: 10px 20px;
  border-radius: 30px;
  background-image: linear-gradient(45deg, #6ab1d7 0%, #33d9de 50%, #002878 100%);
  background-position: 100% 0;
  background-size: 200% 200%;
  font-family: 'Montserrat', sans-serif;
  font-size: 16px;
  font-weight: 200;
  color: white;
  box-shadow: 0 16px 32px 0 rgba(0, 40, 120, .35);
  transition: .5s;
}
.pressed-button:hover {
  box-shadow: 0 0 0 0 rgba(0, 40, 120, 0);
  background-position: 0 0;
}

</style>

</html>